### ISSUE TITLE
Bug: Colours Refusing To Change

### ISSUE THREAD

**Issue by JaiRelan** [RyanFitzgerald/devportfolio#102]
Hi Ryan,
I just wanted to start out by telling you how much I love this template. You've really broken everything down amazingly and I've been looking for a good template to use for my website and out of the ~500 templates I've been through, I love yours the most.

Just wanted to report a bug... I'm trying to change the colours which have been defined in the styles.scss located here (`devportfolio-master/scss/styles.scss`).

This is how my styles.scss looks:

```css
// Define base and accent colors
$base-color: #FF0000;
$base-color-hover: darken($base-color, 20%);

// Define background colors
$background: #FF0000;
$background-alt: #f2f2f5;

// Define border colors
$border: #dcd9d9;

// Define text colors
$heading: #374054;
$text: #74808a;
```
But this is how the page rendered looks:
![Screenshot 2020-10-05 at 9 17 24 PM](https://user-images.githubusercontent.com/40684950/95101765-2d141100-0750-11eb-93bb-b7d23269fd35.png)

Is this a bug or something which I'm doing wrong?

Thanks a ton,
JR

**Comment by RyanFitzgerald** [comment]
Hi JR,

Do you have gulp running? The `.scss` files need to be recompiled back into CSS (which the page then loads).

Regards,
Ryan

**Comment by JaiRelan** [comment]
> Hi JR,
> 
> Do you have gulp running? The `.scss` files need to be recompiled back into CSS (which the page then loads).
> 
> Regards,
> Ryan

Hi Ryan,
Thanks for the prompt reply. I don't remember seeing any instructions in the README asking me to install Gulp. May have missed that. 

I've downloaded gulp-cli@2.3.0 but I'm not sure how to go about running it (I'm new to web development). Could you please help me here?

Thanks,
Jai

**Comment by RyanFitzgerald** [comment]
I apologize for the delay. Once you install the dependencies via `npm install` in the repo, you should be able to either run `npm run watch` or `gulp watch` (if installed globally) to get it going.

**Comment by JaiRelan** [comment]
Hey,
Thanks for the response... I tried running the following:

```
jairelan@Relans-Mac-Mini devportfolio-master % npm run watch

> devportfolio-template@1.2.2 watch /Users/jairelan/Desktop/devportfolio-master
> gulp watch

[09:11:23] Using gulpfile ~/Desktop/devportfolio-master/gulpfile.js
[09:11:23] Starting 'watch'...

```
but then bash get's stuck at `Starting 'watch'...` and refuse to move on any further.

Am I doing something wrong?

I'm a python lad so I'm sorry for not knowing the basics so it would be great if you could help.

**Comment by RyanFitzgerald** [comment]
No worries! I believe that is the expected output. You would only see additional messages once you make changes to the project SCSS / JS which triggers a recompile.

**Comment by JaiRelan** [comment]
Ah perfect! Got it up and running. Thank you so much @RyanFitzgerald
