### ISSUE TITLE
Dynamically change footer copyright year

### ISSUE THREAD

**Issue by vikasganiga05** [RyanFitzgerald/devportfolio#117]
Change the footer copyright static year to dynamic using JavaScript `Date()` Object.

#### Screenshot

![image](https://user-images.githubusercontent.com/74750414/118297439-c764e000-b4fb-11eb-80c1-44dc4a648580.png)

#### Solution
Change the static year to the following dynamically created year.
```js
const currentYear = new Date().getFullYear();    // 2021
```

**Comment by mpiffari** [comment]
Can you give more advice on how to use this piece of code and where to put it?

**Comment by vikasganiga05** [comment]
> Can you give more advice on how to use this piece of code and where to put it?

Yeah sure, follow these steps.

**Step 1 :** On `index.html` surround the year(2020) text in [line:240](https://github.com/RyanFitzgerald/devportfolio/blob/bbbd40d6ca552ff10f6bf1fff4c1c86ba9816b8b/index.html#L240) with a `span` tag and Add `current-year` id attribute to it.
```diff
- Copyright &copy; 2020 YOUR NAME
+ Copyright &copy; <span id="current-year">2020</span> YOUR NAME
```
**Step 2 :** Add the bellow code inside `js/scripts.js` 
```js
// Show current year
$('#current-year').text(new Date().getFullYear());
```
Done :+1:

**Comment by RyanFitzgerald** [comment]
Thanks for the response @vikasganiga05 ! Feel free to PR this and I'd be happy to merge it.

**Comment by vikasganiga05** [comment]
> Thanks for the response @vikasganiga05 ! Feel free to PR this and I'd be happy to merge it.

Sorry for the late reply. I like to work on this issue :slightly_smiling_face:

**Comment by vikasganiga05** [comment]
I created a PR for this issue. Please review it :slightly_smiling_face: :+1:

**Comment by RyanFitzgerald** [comment]
Thanks for getting that PR up, merged!
