### ISSUE TITLE
Projects go missing when there is no image

### ISSUE THREAD

**Issue by AnkitSiva** [RyanFitzgerald/devportfolio#31]
When the image tag is removed and the screen width > 768 px, project cards are missing.

**Comment by RyanFitzgerald** [comment]
Hi,

This was addressed in release 1.2.1. For more information on how to add projects without images, [see here](https://github.com/RyanFitzgerald/devportfolio#projects-without-images).

Hope that helps! If you some reason this isn't what you're referring to, let me know and I'll re-open.

Ryan

**Comment by AnkitSiva** [comment]
Sorry about the duplicate issue. Didn't see that it was solved. Thanks a lot!

**Comment by RyanFitzgerald** [comment]
Not a problem, I appreciate you creating the issue regardless!
