### ISSUE TITLE
node-sass build fails when running npm install

### ISSUE THREAD

**Issue by jaredcaraway** [RyanFitzgerald/devportfolio#45]
I'm not sure if this is something with my local configuration, but when running `npm install` on a fresh clone of this repo, the node-sass dependency failed to install. This prevented Gulp from working properly. After a quick Googling, [I found a recommendation in the issues on the node-sass repo](https://github.com/sass/node-sass/issues/1980#issuecomment-332134196) that solved my issue. I ran this command:

`yarn add node-sass`

...and everything appears to work as intended. Just wanted to drop this pointer for anyone else who might run into the same issue. (Note: this assumes you've got Yarn installed as well.)

Edit: It does seem to be an issue with my particular setup. I tried installing BrowserSync via NPM and it also failed...

**Comment by RyanFitzgerald** [comment]
This appears to be fixed from updating the dependencies thanks to @sav-valerio. If this still occurs, please re-open and I'll investigate further.
