### ISSUE TITLE
Missing social button for LinkedIn

### ISSUE THREAD

**Issue by DevS1993** [RyanFitzgerald/devportfolio#47]
Hey, thanks man. Really cool and simple template.

Since this is a dev-professional portfolio, i feel link LinkedIn should be present along GitHub & stackoverflow links.

**Comment by RyanFitzgerald** [comment]
Good call! That should definitely be added. Thanks for the suggestion.

**Comment by RyanFitzgerald** [comment]
Fixed via #48
