### ISSUE TITLE
![image](https://user-images.githubusercontent.com/19364203/77529210-79bc8c80-6e8f-11ea-8f59-03ffb413a7ad.png)

### ISSUE THREAD

**Issue by NikulGoyani369** [RyanFitzgerald/devportfolio#84]
![image](https://user-images.githubusercontent.com/19364203/77529210-79bc8c80-6e8f-11ea-8f59-03ffb413a7ad.png)

@zkhan96  do you now all step how to run this project after clone in my laptop??
because when I run this project the process is not going further after mentioning in image,

_Originally posted by @NikulGoyani369 in https://github.com/RyanFitzgerald/devportfolio/issues/81#issuecomment-603774973_

**Comment by RyanFitzgerald** [comment]
Should be resolved in `1.2.2`. Try grabbing the latest files, removing your current `/node_modules` and rerunning `npm install`.
