### ISSUE TITLE
color scheme changes not taking effect

### ISSUE THREAD

**Issue by nickhuang25** [RyanFitzgerald/devportfolio#88]
Hi Ryan, thanks for a great template! I'm running into an issue where color scheme changes made in the variable section of styles.scss are not taking effect. I made the edits as outlined in the general section of  your Readme. Would really appreciate if you could point me in the right direction on this.

**Comment by RyanFitzgerald** [comment]
Hey Nick, not a problem, I'm glad you like it! Without having more detail about your issue it's hard to say for sure, but as a first step, do you have Gulp running without errors? It sounds like it may not be compiling as changes made in `styles.scss` only really take effect once compiled successfully.

**Comment by nickhuang25** [comment]
Thanks for the quick response Ryan! I redownloaded my gulp dependencies and it resolved the issue.
